### ISSUE TITLE
How to deploy in production?

### ISSUE THREAD

**Issue by mmraghavendra** [vassiliy/heroku-angular2-seed#1]
I am seeing below message in console.

Angular 2 is running in the development mode. Call enableProdMode() to enable the production mode.

Please let me know where to call enableProdMode()..

Thanks..

**Comment by vassiliy** [comment]
Implemented in [ebd1153](https://github.com/vassiliy/heroku-angular2-seed/commit/ebd1153bf4b443ae646bd3aee7e11087c9e6e64c).

Please check the [live deploy](https://cryptic-earth-70241.herokuapp.com).

Thank you for your attention.

**Comment by mmraghavendra** [comment]
It saved my time.. thank you :-)
